// Code generated by "stringer -type=CandyType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CandyTypeO-0]
	_ = x[CandyTypeI-1]
	_ = x[CandyTypeT-2]
	_ = x[CandyTypeJ-3]
	_ = x[CandyTypeL-4]
	_ = x[CandyTypeS-5]
	_ = x[CandyTypeZ-6]
}

const _CandyType_name = "CandyTypeOCandyTypeICandyTypeTCandyTypeJCandyTypeLCandyTypeSCandyTypeZ"

var _CandyType_index = [...]uint8{0, 10, 20, 30, 40, 50, 60, 70}

func (i CandyType) String() string {
	if i >= CandyType(len(_CandyType_index)-1) {
		return "CandyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CandyType_name[_CandyType_index[i]:_CandyType_index[i+1]]
}
