name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install SDL
      run: sudo apt update && sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev

    - name: Test
      run: go test ./... -coverprofile=coverage.out

    - name: Upload coverage report to codacy
      uses: brpaz/godacov-action@v1.1.1
      with:
        reportPath: 'coverage.out'
        codacyToken: ${{ secrets.CODACY_TOKEN }}
        commitId: ${{ github.sha }}
